name: build

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: checkout
      uses: actions/checkout@v2

    - name: setup VC-LTL
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: nuget install VC-LTL

    - name: setup xmake
      uses: xmake-io/github-action-setup-xmake@v1

    - name: configure
      run: xmake f -a x86

    - name: build
      run: xmake

    - name: upload
      uses: actions/upload-artifact@v3
      with:
        name: perfect
        path: build/release
